contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #variantcalling channel"
    url: https://nfcore.slack.com/channels/variantcalling
    about: Discussion about the nf-core/variantcalling pipeline
