name: sanger-tol LSF tests

on:
  workflow_dispatch:

jobs:
  run-tower:
    name: Run LSF tests
    runs-on: ubuntu-latest
    steps:
      - name: Launch workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: TOL_Farm_LSF_4GB
          revision: ${{ github.sha }}
          workdir: /lustre/scratch122/tol/teams/tolit/nf-tower-agent/work/${{ github.repository }}/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "/lustre/scratch122/tol/teams/tolit/nf-tower-agent/results/${{ github.repository }}/results-${{ github.sha }}"
            }
          profiles: test_align,sanger,singularity,cleanup

      - uses: actions/upload-artifact@v4
        with:
          name: Tower debug log file
          path: |
            tower_action_*.log
            tower_action_*.json
